spring.application.name=servico-vendas
server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:ctn_db_ecommerce_vendas}:5432/${DB_NAME:db_ecommerce_vendas}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true

spring.jpa.hibernate.ddl-auto=none